/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "../common.js"
  

  export interface SimpleLendingPoolInterface extends Interface {
    getFunction(nameOrSignature: "UPGRADE_INTERFACE_VERSION" | "borrowFee" | "borrowed" | "collateral" | "createPoolInfo" | "depositBorrow" | "depositLend" | "getPoolState" | "initialize" | "lendFee" | "owner" | "poolBaseInfo" | "poolDataInfo" | "poolLength" | "proxiableUUID" | "renounceOwnership" | "repay" | "setFee" | "supplied" | "transferOwnership" | "upgradeToAndCall" | "withdrawCollateral" | "withdrawLend"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "DepositBorrow" | "DepositLend" | "Initialized" | "OwnershipTransferred" | "Repay" | "SetFee" | "StateChange" | "Upgraded" | "WithdrawCollateral" | "WithdrawLend"): EventFragment;

    encodeFunctionData(functionFragment: 'UPGRADE_INTERFACE_VERSION', values?: undefined): string;
encodeFunctionData(functionFragment: 'borrowFee', values?: undefined): string;
encodeFunctionData(functionFragment: 'borrowed', values: [BigNumberish, AddressLike]): string;
encodeFunctionData(functionFragment: 'collateral', values: [BigNumberish, AddressLike]): string;
encodeFunctionData(functionFragment: 'createPoolInfo', values: [BigNumberish, BigNumberish, BigNumberish, BigNumberish, BigNumberish, AddressLike, AddressLike, AddressLike, AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'depositBorrow', values: [BigNumberish, BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'depositLend', values: [BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'getPoolState', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'initialize', values: [BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'lendFee', values?: undefined): string;
encodeFunctionData(functionFragment: 'owner', values?: undefined): string;
encodeFunctionData(functionFragment: 'poolBaseInfo', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'poolDataInfo', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'poolLength', values?: undefined): string;
encodeFunctionData(functionFragment: 'proxiableUUID', values?: undefined): string;
encodeFunctionData(functionFragment: 'renounceOwnership', values?: undefined): string;
encodeFunctionData(functionFragment: 'repay', values: [BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'setFee', values: [BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'supplied', values: [BigNumberish, AddressLike]): string;
encodeFunctionData(functionFragment: 'transferOwnership', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'upgradeToAndCall', values: [AddressLike, BytesLike]): string;
encodeFunctionData(functionFragment: 'withdrawCollateral', values: [BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'withdrawLend', values: [BigNumberish, BigNumberish]): string;

    decodeFunctionResult(functionFragment: 'UPGRADE_INTERFACE_VERSION', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'borrowFee', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'borrowed', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'collateral', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'createPoolInfo', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'depositBorrow', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'depositLend', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getPoolState', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'initialize', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'lendFee', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'owner', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'poolBaseInfo', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'poolDataInfo', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'poolLength', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'proxiableUUID', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'renounceOwnership', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'repay', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setFee', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'supplied', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'transferOwnership', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'upgradeToAndCall', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'withdrawCollateral', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'withdrawLend', data: BytesLike): Result;
  }

  
    export namespace DepositBorrowEvent {
      export type InputTuple = [user: AddressLike, pid: BigNumberish, collateralAmt: BigNumberish, borrowAmt: BigNumberish];
      export type OutputTuple = [user: string, pid: bigint, collateralAmt: bigint, borrowAmt: bigint];
      export interface OutputObject {user: string, pid: bigint, collateralAmt: bigint, borrowAmt: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace DepositLendEvent {
      export type InputTuple = [user: AddressLike, pid: BigNumberish, amount: BigNumberish];
      export type OutputTuple = [user: string, pid: bigint, amount: bigint];
      export interface OutputObject {user: string, pid: bigint, amount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace InitializedEvent {
      export type InputTuple = [version: BigNumberish];
      export type OutputTuple = [version: bigint];
      export interface OutputObject {version: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace OwnershipTransferredEvent {
      export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
      export type OutputTuple = [previousOwner: string, newOwner: string];
      export interface OutputObject {previousOwner: string, newOwner: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace RepayEvent {
      export type InputTuple = [user: AddressLike, pid: BigNumberish, amount: BigNumberish];
      export type OutputTuple = [user: string, pid: bigint, amount: bigint];
      export interface OutputObject {user: string, pid: bigint, amount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace SetFeeEvent {
      export type InputTuple = [lendFee: BigNumberish, borrowFee: BigNumberish];
      export type OutputTuple = [lendFee: bigint, borrowFee: bigint];
      export interface OutputObject {lendFee: bigint, borrowFee: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace StateChangeEvent {
      export type InputTuple = [pid: BigNumberish, beforeState: BigNumberish, afterState: BigNumberish];
      export type OutputTuple = [pid: bigint, beforeState: bigint, afterState: bigint];
      export interface OutputObject {pid: bigint, beforeState: bigint, afterState: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace UpgradedEvent {
      export type InputTuple = [implementation: AddressLike];
      export type OutputTuple = [implementation: string];
      export interface OutputObject {implementation: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace WithdrawCollateralEvent {
      export type InputTuple = [user: AddressLike, pid: BigNumberish, amount: BigNumberish];
      export type OutputTuple = [user: string, pid: bigint, amount: bigint];
      export interface OutputObject {user: string, pid: bigint, amount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace WithdrawLendEvent {
      export type InputTuple = [user: AddressLike, pid: BigNumberish, amount: BigNumberish];
      export type OutputTuple = [user: string, pid: bigint, amount: bigint];
      export interface OutputObject {user: string, pid: bigint, amount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface SimpleLendingPool extends BaseContract {
    
    connect(runner?: ContractRunner | null): SimpleLendingPool;
    waitForDeployment(): Promise<this>;

    interface: SimpleLendingPoolInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    UPGRADE_INTERFACE_VERSION: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    borrowFee: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    borrowed: TypedContractMethod<
      [arg0: BigNumberish, arg1: AddressLike, ],
      [bigint],
      'view'
    >
    

    
    collateral: TypedContractMethod<
      [arg0: BigNumberish, arg1: AddressLike, ],
      [bigint],
      'view'
    >
    

    
    createPoolInfo: TypedContractMethod<
      [_settleTime: BigNumberish, _endTime: BigNumberish, _interestRate: BigNumberish, _maxSupply: BigNumberish, _martgageRate: BigNumberish, _lendToken: AddressLike, _borrowToken: AddressLike, _spToken: AddressLike, _jpToken: AddressLike, _autoLiquidateThreshold: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    depositBorrow: TypedContractMethod<
      [pid: BigNumberish, collateralAmt: BigNumberish, borrowAmt: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    depositLend: TypedContractMethod<
      [pid: BigNumberish, amount: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    getPoolState: TypedContractMethod<
      [pid: BigNumberish, ],
      [bigint],
      'view'
    >
    

    
    initialize: TypedContractMethod<
      [_lendFee: BigNumberish, _borrowFee: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    lendFee: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    owner: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    poolBaseInfo: TypedContractMethod<
      [arg0: BigNumberish, ],
      [[bigint, bigint, bigint, bigint, bigint, bigint, bigint, string, string, bigint, string, string, bigint] & {settleTime: bigint, endTime: bigint, interestRate: bigint, maxSupply: bigint, lendSupply: bigint, borrowSupply: bigint, martgageRate: bigint, lendToken: string, borrowToken: string, state: bigint, spCoin: string, jpCoin: string, autoLiquidateThreshold: bigint }],
      'view'
    >
    

    
    poolDataInfo: TypedContractMethod<
      [arg0: BigNumberish, ],
      [[bigint, bigint, bigint, bigint, bigint, bigint] & {settleAmountLend: bigint, settleAmountBorrow: bigint, finishAmountLend: bigint, finishAmountBorrow: bigint, liquidationAmounLend: bigint, liquidationAmounBorrow: bigint }],
      'view'
    >
    

    
    poolLength: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    proxiableUUID: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    renounceOwnership: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    repay: TypedContractMethod<
      [pid: BigNumberish, amount: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    setFee: TypedContractMethod<
      [_lendFee: BigNumberish, _borrowFee: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    supplied: TypedContractMethod<
      [arg0: BigNumberish, arg1: AddressLike, ],
      [bigint],
      'view'
    >
    

    
    transferOwnership: TypedContractMethod<
      [newOwner: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    upgradeToAndCall: TypedContractMethod<
      [newImplementation: AddressLike, data: BytesLike, ],
      [void],
      'payable'
    >
    

    
    withdrawCollateral: TypedContractMethod<
      [pid: BigNumberish, amount: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    withdrawLend: TypedContractMethod<
      [pid: BigNumberish, amount: BigNumberish, ],
      [void],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'UPGRADE_INTERFACE_VERSION'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'borrowFee'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'borrowed'): TypedContractMethod<
      [arg0: BigNumberish, arg1: AddressLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'collateral'): TypedContractMethod<
      [arg0: BigNumberish, arg1: AddressLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'createPoolInfo'): TypedContractMethod<
      [_settleTime: BigNumberish, _endTime: BigNumberish, _interestRate: BigNumberish, _maxSupply: BigNumberish, _martgageRate: BigNumberish, _lendToken: AddressLike, _borrowToken: AddressLike, _spToken: AddressLike, _jpToken: AddressLike, _autoLiquidateThreshold: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'depositBorrow'): TypedContractMethod<
      [pid: BigNumberish, collateralAmt: BigNumberish, borrowAmt: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'depositLend'): TypedContractMethod<
      [pid: BigNumberish, amount: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'getPoolState'): TypedContractMethod<
      [pid: BigNumberish, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'initialize'): TypedContractMethod<
      [_lendFee: BigNumberish, _borrowFee: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'lendFee'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'owner'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'poolBaseInfo'): TypedContractMethod<
      [arg0: BigNumberish, ],
      [[bigint, bigint, bigint, bigint, bigint, bigint, bigint, string, string, bigint, string, string, bigint] & {settleTime: bigint, endTime: bigint, interestRate: bigint, maxSupply: bigint, lendSupply: bigint, borrowSupply: bigint, martgageRate: bigint, lendToken: string, borrowToken: string, state: bigint, spCoin: string, jpCoin: string, autoLiquidateThreshold: bigint }],
      'view'
    >;
getFunction(nameOrSignature: 'poolDataInfo'): TypedContractMethod<
      [arg0: BigNumberish, ],
      [[bigint, bigint, bigint, bigint, bigint, bigint] & {settleAmountLend: bigint, settleAmountBorrow: bigint, finishAmountLend: bigint, finishAmountBorrow: bigint, liquidationAmounLend: bigint, liquidationAmounBorrow: bigint }],
      'view'
    >;
getFunction(nameOrSignature: 'poolLength'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'proxiableUUID'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'renounceOwnership'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'repay'): TypedContractMethod<
      [pid: BigNumberish, amount: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setFee'): TypedContractMethod<
      [_lendFee: BigNumberish, _borrowFee: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'supplied'): TypedContractMethod<
      [arg0: BigNumberish, arg1: AddressLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'transferOwnership'): TypedContractMethod<
      [newOwner: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'upgradeToAndCall'): TypedContractMethod<
      [newImplementation: AddressLike, data: BytesLike, ],
      [void],
      'payable'
    >;
getFunction(nameOrSignature: 'withdrawCollateral'): TypedContractMethod<
      [pid: BigNumberish, amount: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'withdrawLend'): TypedContractMethod<
      [pid: BigNumberish, amount: BigNumberish, ],
      [void],
      'nonpayable'
    >;

    getEvent(key: 'DepositBorrow'): TypedContractEvent<DepositBorrowEvent.InputTuple, DepositBorrowEvent.OutputTuple, DepositBorrowEvent.OutputObject>;
getEvent(key: 'DepositLend'): TypedContractEvent<DepositLendEvent.InputTuple, DepositLendEvent.OutputTuple, DepositLendEvent.OutputObject>;
getEvent(key: 'Initialized'): TypedContractEvent<InitializedEvent.InputTuple, InitializedEvent.OutputTuple, InitializedEvent.OutputObject>;
getEvent(key: 'OwnershipTransferred'): TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
getEvent(key: 'Repay'): TypedContractEvent<RepayEvent.InputTuple, RepayEvent.OutputTuple, RepayEvent.OutputObject>;
getEvent(key: 'SetFee'): TypedContractEvent<SetFeeEvent.InputTuple, SetFeeEvent.OutputTuple, SetFeeEvent.OutputObject>;
getEvent(key: 'StateChange'): TypedContractEvent<StateChangeEvent.InputTuple, StateChangeEvent.OutputTuple, StateChangeEvent.OutputObject>;
getEvent(key: 'Upgraded'): TypedContractEvent<UpgradedEvent.InputTuple, UpgradedEvent.OutputTuple, UpgradedEvent.OutputObject>;
getEvent(key: 'WithdrawCollateral'): TypedContractEvent<WithdrawCollateralEvent.InputTuple, WithdrawCollateralEvent.OutputTuple, WithdrawCollateralEvent.OutputObject>;
getEvent(key: 'WithdrawLend'): TypedContractEvent<WithdrawLendEvent.InputTuple, WithdrawLendEvent.OutputTuple, WithdrawLendEvent.OutputObject>;

    filters: {
      
      'DepositBorrow(address,uint256,uint256,uint256)': TypedContractEvent<DepositBorrowEvent.InputTuple, DepositBorrowEvent.OutputTuple, DepositBorrowEvent.OutputObject>;
      DepositBorrow: TypedContractEvent<DepositBorrowEvent.InputTuple, DepositBorrowEvent.OutputTuple, DepositBorrowEvent.OutputObject>;
    

      'DepositLend(address,uint256,uint256)': TypedContractEvent<DepositLendEvent.InputTuple, DepositLendEvent.OutputTuple, DepositLendEvent.OutputObject>;
      DepositLend: TypedContractEvent<DepositLendEvent.InputTuple, DepositLendEvent.OutputTuple, DepositLendEvent.OutputObject>;
    

      'Initialized(uint64)': TypedContractEvent<InitializedEvent.InputTuple, InitializedEvent.OutputTuple, InitializedEvent.OutputObject>;
      Initialized: TypedContractEvent<InitializedEvent.InputTuple, InitializedEvent.OutputTuple, InitializedEvent.OutputObject>;
    

      'OwnershipTransferred(address,address)': TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
      OwnershipTransferred: TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
    

      'Repay(address,uint256,uint256)': TypedContractEvent<RepayEvent.InputTuple, RepayEvent.OutputTuple, RepayEvent.OutputObject>;
      Repay: TypedContractEvent<RepayEvent.InputTuple, RepayEvent.OutputTuple, RepayEvent.OutputObject>;
    

      'SetFee(uint256,uint256)': TypedContractEvent<SetFeeEvent.InputTuple, SetFeeEvent.OutputTuple, SetFeeEvent.OutputObject>;
      SetFee: TypedContractEvent<SetFeeEvent.InputTuple, SetFeeEvent.OutputTuple, SetFeeEvent.OutputObject>;
    

      'StateChange(uint256,uint256,uint256)': TypedContractEvent<StateChangeEvent.InputTuple, StateChangeEvent.OutputTuple, StateChangeEvent.OutputObject>;
      StateChange: TypedContractEvent<StateChangeEvent.InputTuple, StateChangeEvent.OutputTuple, StateChangeEvent.OutputObject>;
    

      'Upgraded(address)': TypedContractEvent<UpgradedEvent.InputTuple, UpgradedEvent.OutputTuple, UpgradedEvent.OutputObject>;
      Upgraded: TypedContractEvent<UpgradedEvent.InputTuple, UpgradedEvent.OutputTuple, UpgradedEvent.OutputObject>;
    

      'WithdrawCollateral(address,uint256,uint256)': TypedContractEvent<WithdrawCollateralEvent.InputTuple, WithdrawCollateralEvent.OutputTuple, WithdrawCollateralEvent.OutputObject>;
      WithdrawCollateral: TypedContractEvent<WithdrawCollateralEvent.InputTuple, WithdrawCollateralEvent.OutputTuple, WithdrawCollateralEvent.OutputObject>;
    

      'WithdrawLend(address,uint256,uint256)': TypedContractEvent<WithdrawLendEvent.InputTuple, WithdrawLendEvent.OutputTuple, WithdrawLendEvent.OutputObject>;
      WithdrawLend: TypedContractEvent<WithdrawLendEvent.InputTuple, WithdrawLendEvent.OutputTuple, WithdrawLendEvent.OutputObject>;
    
    };
  }