/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { AuctionUpgradeable } from "./AuctionUpgradeable";
export type { MyNFT } from "./MyNFT";
export type { MyToken } from "./MyToken";
