/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IERC20__factory } from './IERC20__factory.js';
export { SimpleLendingPool__factory } from './SimpleLendingPool__factory.js';