/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as simpleLendingPoolSol from './SimpleLendingPool.sol/index.js';
export * as mocks from './mocks/index.js';
export { SimpleLendingPoolProxy__factory } from './SimpleLendingPoolProxy__factory.js';
export { SimpleLendingPoolV2__factory } from './SimpleLendingPoolV2__factory.js';