/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { Addressable } from "ethers";
import { Contract, ContractFactory, ContractTransactionResponse, Interface } from "ethers"
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers"
import type { NonPayableOverrides } from "../common.js"
  import type { ProxyArtifacts, ProxyArtifactsInterface } from "../ProxyArtifacts.js";

  const _abi = [
  {
    "inputs": [],
    "name": "proxyContractName",
    "outputs": [
      {
        "internalType": "string",
        "name": "",
        "type": "string"
      }
    ],
    "stateMutability": "pure",
    "type": "function"
  }
] as const;

  const _bytecode = "0x608080604052346100155760f5908161001a8239f35b5f80fdfe60806004361015600d575f80fd5b5f3560e01c621b4c7b14601e575f80fd5b3460bb575f36600319011260bb57604080820182811067ffffffffffffffff82111760a7578152600c825260206b4552433139363750726f787960a01b60208401528151928391602083528151918260208501525f5b83811060925750505f83830185015250601f01601f19168101030190f35b81810183015187820187015286945082016074565b634e487b7160e01b5f52604160045260245ffd5b5f80fdfea26469706673582212201034b68ad854fac49bbb293aac9d16cb619e16f81272cba134e19b6037c6646c64736f6c63430008170033";

  
      type ProxyArtifactsConstructorParams = [signer?: Signer] | ConstructorParameters<typeof ContractFactory>;

      const isSuperArgs = (xs: ProxyArtifactsConstructorParams): xs is ConstructorParameters<typeof ContractFactory> =>
        xs.length > 1
    

  export class ProxyArtifacts__factory extends ContractFactory {
    
      constructor(...args: ProxyArtifactsConstructorParams) {
        if (isSuperArgs(args)) {
          super(...args);
        } else {
          super(_abi, _bytecode, args[0]);
        }
        
      }
    
    override getDeployTransaction(overrides?: NonPayableOverrides & { from?: string }): Promise<ContractDeployTransaction> {
      return super.getDeployTransaction(overrides || {});
    };
    override deploy(overrides?: NonPayableOverrides & { from?: string }) {
      return super.deploy(overrides || {}) as Promise<ProxyArtifacts & {
        deploymentTransaction(): ContractTransactionResponse;
      }>;
    }
    override connect(runner: ContractRunner | null): ProxyArtifacts__factory {
      return super.connect(runner) as ProxyArtifacts__factory;
    }
    
    
    static readonly bytecode = _bytecode;
    static readonly abi = _abi;
    static createInterface(): ProxyArtifactsInterface {
      return new Interface(_abi) as ProxyArtifactsInterface;
    }
    
    override attach(address: string | Addressable): ProxyArtifacts {
      return super.attach(address) as ProxyArtifacts;
    }
  static connect(address: string, runner?: ContractRunner | null): ProxyArtifacts {
      return new Contract(address, _abi, runner) as unknown as ProxyArtifacts;
    }
  }

  
  