/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */


import { ethers } from 'ethers'
import { DeployContractOptions, FactoryOptions, HardhatEthersHelpers as HardhatEthersHelpersBase} from "@nomicfoundation/hardhat-ethers/types";

import * as Contracts from "./index.js";

declare module "@nomicfoundation/hardhat-ethers/types" {
  interface HardhatEthersHelpers extends HardhatEthersHelpersBase {
  getContractFactory(name: 'MockERC20', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.MockERC20__factory>
getContractFactory(name: 'IERC20', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.IERC20__factory>
getContractFactory(name: 'SimpleLendingPool', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.SimpleLendingPool__factory>
getContractFactory(name: 'SimpleLendingPoolProxy', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.SimpleLendingPoolProxy__factory>
getContractFactory(name: 'SimpleLendingPoolV2', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.SimpleLendingPoolV2__factory>

  getContractAt(name: 'MockERC20', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.MockERC20>
getContractAt(name: 'IERC20', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.IERC20>
getContractAt(name: 'SimpleLendingPool', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.SimpleLendingPool>
getContractAt(name: 'SimpleLendingPoolProxy', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.SimpleLendingPoolProxy>
getContractAt(name: 'SimpleLendingPoolV2', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.SimpleLendingPoolV2>

  deployContract(name: 'MockERC20', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.MockERC20>
deployContract(name: 'IERC20', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IERC20>
deployContract(name: 'SimpleLendingPool', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.SimpleLendingPool>
deployContract(name: 'SimpleLendingPoolProxy', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.SimpleLendingPoolProxy>
deployContract(name: 'SimpleLendingPoolV2', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.SimpleLendingPoolV2>

  deployContract(name: 'MockERC20', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.MockERC20>
deployContract(name: 'IERC20', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IERC20>
deployContract(name: 'SimpleLendingPool', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.SimpleLendingPool>
deployContract(name: 'SimpleLendingPoolProxy', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.SimpleLendingPoolProxy>
deployContract(name: 'SimpleLendingPoolV2', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.SimpleLendingPoolV2>

    // default types
    getContractFactory(
      name: string,
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<ethers.ContractFactory>;
    getContractFactory(
      abi: any[],
      bytecode: ethers.BytesLike,
      signer?: ethers.Signer
    ): Promise<ethers.ContractFactory>;
    getContractAt(
      nameOrAbi: string | any[],
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
  }
}
  