/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as simpleLendingPoolSol from './SimpleLendingPool.sol/index.js';
export type { simpleLendingPoolSol };
import type * as mocks from './mocks/index.js';
export type { mocks };
export type { SimpleLendingPoolProxy } from './SimpleLendingPoolProxy.js';
export type { SimpleLendingPoolV2 } from './SimpleLendingPoolV2.js';
export * as factories from './factories/index.js';
export type { MockERC20 } from './mocks/MockERC20.js';
export { MockERC20__factory } from './factories/mocks/MockERC20__factory.js';
export type { IERC20 } from './SimpleLendingPool.sol/IERC20.js';
export { IERC20__factory } from './factories/SimpleLendingPool.sol/IERC20__factory.js';
export type { SimpleLendingPool } from './SimpleLendingPool.sol/SimpleLendingPool.js';
export { SimpleLendingPool__factory } from './factories/SimpleLendingPool.sol/SimpleLendingPool__factory.js';
export { SimpleLendingPoolProxy__factory } from './factories/SimpleLendingPoolProxy__factory.js';
export { SimpleLendingPoolV2__factory } from './factories/SimpleLendingPoolV2__factory.js';